import { Geist, Azeret_Mono as Geist_Mono } from "next/font/google"
import "./globals.css"
import ThemeProviderWrapper from "@/components/theme-provider-wrapper"
import Header from "@/components/header"
import { ClerkProvider } from "@clerk/nextjs"
import { dark } from "@clerk/themes"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata = {
  title: "CareerCraft AI",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en" suppressHydrationWarning>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}>
          <ThemeProviderWrapper>
            <Header />
            <main className="min-h-screen">{children}</main>
            <footer className="bg-muted/50 py-12">
              <div className="container mx-auto px-4 text-center text-gray-200">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
              </div>
            </footer>
          </ThemeProviderWrapper>
        </body>
      </html>
    </ClerkProvider>
  )
}

